homejango/homejango/urls.py
from django.contrib import admin
from django.urls import path, include  # include добавленный вручную метод для вывода url
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include('main.urls')),
                  path('users/', include('users.urls', namespace='users')),
                  path('service/', include('service.urls')),
              ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += [
        path('__debug__/', include(debug_toolbar.urls, namespace='djdt')),
    ]

homejango/main/urls.py
from django.urls import path
from . import views
from .views import ReviewsListView, ReviewCreateView

urlpatterns = [
   path('', views.index, name='home'),
   path('about', views.about, name='about'),
   path('contacts', views.contacts, name='contacts'),
   # path('reviews', views.reviews, name='reviews'),
   path('reviews/delete/<int:pk>/', views.ReviewDelete.as_view(), name='reviews_delete'),
   # path('reviews/delete/<int:id>/', views.reviews_delete, name='reviews_delete'),
   path('reviews/', ReviewsListView.as_view(), name='reviews-list'),
   path('reviews/add/', ReviewCreateView.as_view(), name='review-add'),
   # path('reviews', views.reviews, name='reviews'),
   # path('reviews/delete/<int:id>/', views.reviews_delete, name='reviews_delete'),
   path('personal_doctor', views.personal_doctor, name='personal_doctor'),
   path('gruming', views.gruming, name='gruming'),
]

homejango/users/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path
from . import views


app_name = 'users'
urlpatterns = [
   # для вывода нужной страницы после входа/выхода нужно прописать или
   # функции get-succes_url или в settings  LOGOUT/LOGIN_REDIRECT_URL
   path('login/', views.LoginUser.as_view(), name='login'),     # для
   path('logout/', LogoutView.as_view(), name='logout'),
   path('register/', views.RegisterUser.as_view(), name='register'),
   path('profile/', views.ProfileUser.as_view(), name='profile'),
   # path('profile/', views.profile_update, name='profile'),
   path('profile/delete/<int:pk>/', views.PetsDelete.as_view(), name='profile_delete'),
   # path('profile/add_pet/', views.profile_add_pet, name='profile_add_pet'),

# большая разница между <int:temp_id>  и <int:pk>. В первом случае просто указываем что это число
   # подходит для функций. Если используем класс надо четко указать id(<int:pk>) или slug
   path('profile/add_pet/', views.AddPets.as_view(), name='profile_add_pet'),
   path('profile/edit_pet/<int:pk>/', views.UpdatePets.as_view(), name='profile_edit_pet'),
]

homejango/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class User(AbstractUser):
    phone = models.CharField(max_length=20, blank=True, null=True, verbose_name='Телефон')

homejango/users/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.forms import inlineformset_factory, formset_factory

from service.forms import PetForms, PetsFormSet
from service.models import Clients, Pets


class LoginUserForm(AuthenticationForm):
    username = forms.CharField(label='Логин',
                               widget=forms.TextInput(attrs={'class': 'form-input'}))
    password = forms.CharField(label='Пароль',
                               widget=forms.PasswordInput(attrs={'class': 'form-input'}))

    class Meta:
        # так делать правильнее чем через поля формы т.к страхует при изменения модели юзера
        model = get_user_model()
        fields = ['username', 'password']


class RegisterUserForm(UserCreationForm):
    username = forms.CharField(label='Логин',
                               widget=forms.TextInput(attrs={'class': 'form-input'}))
    password1 = forms.CharField(label='Пароль',
                                widget=forms.PasswordInput(attrs={'class': 'form-input'}))
    password2 = forms.CharField(label='Повтор Пароля',
                                widget=forms.PasswordInput(attrs={'class': 'form-input'}))
    # firstname = forms.CharField(label='Имя',
    #                            widget=forms.TextInput(attrs={'class': 'form-input'}))
    # lastname = forms.CharField(label='Фамилия',
    #                            widget=forms.TextInput(attrs={'class': 'form-input'}))

    email = forms.EmailField(label='email',
                             widget=forms.TextInput(attrs={'class': 'form-input'}))

    class Meta:
        # так делать правильнее чем через поля формы т.к страхует при изменения модели юзера
        model = get_user_model()
        fields = ['username', 'email', 'first_name', 'last_name', 'password1', 'password2', 'phone']
        labels = {
            'email': 'E-mail',
            'firstname': 'Имя',
            'lastname': 'Фамилия',
            'phone': 'Телефон'

        }

    def сlean_password(self):
        cd = self.cleaned_data
        if cd['password'] != cd['password2']:
            raise forms.ValidationError('Пароли не совпадают')
        return cd['password']

    def clean_email(self):
        email = self.cleaned_data['email']
        if get_user_model().objects.filter(email=email).exists():
            raise forms.ValidationError('Такой email уже существует!!')
        return email


class ProfileUserForm(forms.ModelForm):
    username = forms.CharField(disabled=True, label='Логин',
                               widget=forms.TextInput(attrs={'class': 'form-input'}))
    email = forms.EmailField(disabled=True, label='email',
                             widget=forms.TextInput(attrs={'class': 'form-input'}))
    pets_formset = PetsFormSet

    class Meta:
        model = get_user_model()
        fields = ['username', 'email', 'first_name', 'last_name', 'phone']
        labels = {
            'first_name': 'Имя',
            'last_name': 'Фамилия',
            'phone': 'Телефон'
        }



# PetsFormSet = inlineformset_factory(
#     Clients, Pets, fields=('nickname', 'birthdate', 'breed', 'color', 'id'), extra=1, can_delete=True,
# )

homejango/users/views.py
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout, get_user_model
from django.contrib.auth.decorators import user_passes_test
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LoginView
from django.http import HttpResponse, HttpResponseRedirect, request
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse, reverse_lazy
from django.views.generic import CreateView, UpdateView, DeleteView

from service.forms import PetForms
from service.models import Clients, Pets
from .forms import LoginUserForm, RegisterUserForm

from .forms import ProfileUserForm, PetsFormSet


# Create your views here.


# def login_user(request):       # логин через функцию
#     if request.method == 'POST':
#         form = LoginUserForm(request.POST)
#         if form.is_valid():
#             cd = form.cleaned_data  # коллекция для аутентификации пользователя
#             user = authenticate(request, username=cd['username'], password=cd['password'])
#             if user and user.is_active:
#                 login(request, user)
#                 return HttpResponseRedirect(reverse('home'))
#     else:
#         form = LoginUserForm()
#     return render(request, 'users/login.html', {'form': form})

#
# def logout_user(request):    # логаут через функцию (аздан напрямую в urls.py)
#     logout(request)
#     return HttpResponseRedirect(reverse('users:login'))


class LoginUser(LoginView):  # логин через класс - проверка на валидность сразу встроена
    form_class = LoginUserForm
    template_name = 'users/login.html'
    extra_context = {'title': 'Авторизация'}

    # меняет страницу на которую переходится после успешной авторизаии
    # У нас убрано т.к прописан LOGIN_REDIRECT_URL  в settings - что аналогично
    # def get_success_url(self):
    #     return reverse_lazy('home')


class RegisterUser(CreateView):
    form_class = RegisterUserForm
    template_name = 'users/register.html'
    extra_context = {'title': 'Регистрация'}
    success_url = reverse_lazy('home')

    def form_valid(self, form):
        user = form.save()  # Сохраняем пользователя и получаем экземпляр User

        Clients.objects.create(
            user=user,
            first_name=form.cleaned_data['first_name'],
            last_name=form.cleaned_data['last_name'],
            phone=form.cleaned_data['phone']
        )
        messages.success(self.request, "Регистрация успешно завершена")
        return super().form_valid(form)

# def register(request):
#     if request.method == "POST":
#         form = RegisterUserForm(request.POST)
#         if form.is_valid():
#
#             user = form.save(commit=False)
#             user.set_password(form.cleaned_data['password1'])
#             user.save()
#
#             Clients.objects.create(
#                 user=user,
#                 first_name=form.cleaned_data['first_name'],
#                 last_name=form.cleaned_data['last_name'],
#                 phone=form.cleaned_data['phone']
#             )
#             messages.success(request, "Регистрация успешно завершена")
#             return redirect('home')
#
#     else:
#         form = RegisterUserForm()
#     return render(request, 'users/register.html', {'form': form})


class ProfileUser(LoginRequiredMixin, UpdateView):
    model = get_user_model()
    form_class = ProfileUserForm
    template_name = 'users/profile.html'
    extra_context = {'title': 'Профайл'}
    success_url = reverse_lazy('users:profile')

    def get_object(self, queryset=None):
        return self.request.user

    def form_valid(self, form):
        user = form.save()  # Сохраняем пользователя и получаем экземпляр User

        # Обновляем данные клиента
        Clients.objects.filter(user=user).update(
            first_name=form.cleaned_data['first_name'],
            last_name=form.cleaned_data['last_name'],
            phone=form.cleaned_data['phone']
        )
        messages.success(self.request, "Ваши данные успешно обновлены")
        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        client, created = Clients.objects.get_or_create(user=self.request.user)
        context['pets'] = Pets.objects.filter(clients=client)
        return context
#
#
# def profile_update(request):
#     user = request.user
#     client, created = Clients.objects.get_or_create(user=user)
#     client_id = client.id
#     form = ProfileUserForm(request.POST or None, instance=user)
#     pets = Pets.objects.filter(clients=client_id)
#
#     if request.method == 'POST':
#         if form.is_valid():
#
#             client.first_name = form.cleaned_data['first_name']
#             client.last_name = form.cleaned_data['last_name']
#             client.phone = form.cleaned_data['phone']
#             client.save()
#
#             user.first_name = form.cleaned_data['first_name']
#             user.last_name = form.cleaned_data['last_name']
#             user.phone = form.cleaned_data['phone']
#             user.save()
#             messages.success(request, "Ваши данные успешно обновлены")
#
#
#     return render(request, 'users/profile.html', {
#         'form': form,
#         'pets': pets,
#         'title': 'Профайл'
#     })


# У класса есть минус оносительноф ункции нужна страница для запроса на подтверждене удаления
# или надо переопределять метод  get
class PetsDelete(DeleteView):
    model = Pets
    success_url = reverse_lazy('users:profile')

    def delete(self, request, *args, **kwargs):
        messages.success(self.request, "Питомец успешно удален из профиля")
        return super().delete(request, *args, **kwargs)

    def get(self, request, *args, **kwargs):
        self.object = self.get_object()
        self.object.delete()
        return redirect(self.get_success_url())

# def profile_delete(request, temp_id):
#     pets = Pets.objects.filter(id=temp_id)
#     pets.delete()
#     messages.success(request, "Питомец успешно удален из профиля")
#     return redirect('users:profile')


# def profile_add_pet(request):
#     if request.method == 'POST':
#         pets = PetForms(request.POST)
#         if pets.is_valid():
#             error = check_pets_value_valid(request.POST['nickname'], request.POST['breed'], request.POST['color'])
#             if error == '':
#                 user = request.user
#                 client, created = Clients.objects.get_or_create(user=user)
#                 pet = pets.save(commit=False)
#                 pet.clients = client  # Присваиваем объект client к полю clients
#                 pet.save()
#                 messages.success(request, "Питомец успешно добавлен в профиль")
#                 return redirect('users:profile')
#             else:
#                 messages.error(request, f"{error}")
#                 return render(request, 'users/add_pet.html', {
#                     'pets': pets,
#                 })
#     else:
#         pets = PetForms()
#
#     return render(request, 'users/add_pet.html', {
#         'pets': pets,
#     })
#

class AddPets(CreateView):
    form_class = PetForms
    template_name = 'users/add_pet.html'
    # context_object_name = 'pets'
    success_url = reverse_lazy('users:profile')

    def form_valid(self, form):
        user = self.request.user

        # Получаем или создаем объект Clients для текущего пользователя
        client, created = Clients.objects.get_or_create(user=user)

        # Связываем объект Pets с объектом Clients
        pet = form.save(commit=False)  # Сначала сохраняем форму, не сохраняя ее в базу данных
        pet.clients = client  # Присваиваем объект Clients полю clients модели Pets
        pet.save()  # Сохраняем объект Pets в базу данных
        messages.success(request, "Питомец успешно добавлен в профиль")
        return super().form_valid(form)


class UpdatePets(UpdateView):
    model = Pets
    form_class = PetForms
    template_name = 'users/edit_pet.html'
    # context_object_name = 'pets'
    success_url = reverse_lazy('users:profile')

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        pk = self.kwargs.get('pk')
        temp_pet = get_object_or_404(Pets, id=pk)
        kwargs['instance'] = temp_pet
        return kwargs

    def form_valid(self, form):
        user = self.request.user

        # Получаем или создаем объект Clients для текущего пользователя
        client, created = Clients.objects.get_or_create(user=user)

        # Связываем объект Pets с объектом Clients
        pet = form.save(commit=False)  # Сначала сохраняем форму, не сохраняя ее в базу данных
        pet.clients = client  # Присваиваем объект Clients полю clients модели Pets
        pet.save()  # Сохраняем объект Pets в базу данных
        messages.success(request, "Данные питомца успешно обновлены.")
        return super().form_valid(form)


# def profile_edit_pet(request, temp_id):
#     if request.method == 'POST':
#         pets = PetForms(request.POST)
#         if pets.is_valid():
#             error = check_pets_value_valid(request.POST['nickname'], request.POST['breed'], request.POST['color'])
#             if error == '':
#                 user = request.user
#                 client, created = Clients.objects.get_or_create(user=user)
#                 pet = pets.save(commit=False)
#                 pet.clients = client
#                 pet.save()
#                 messages.success(request, "Данные питомца успешно обновлены.")
#                 return redirect('users:profile')
#             else:
#                 temp_pet = get_object_or_404(Pets, id=temp_id)
#                 value = temp_pet.birthdate.isoformat()
#                 pets = PetForms(instance=temp_pet)
#
#                 messages.error(request, f"{error}")

homejango/users/templates/users/add_pet.html
{% extends 'main/layout.html' %}
{% load static %}

{% block content %}
<h1 class="main_h">Добавление питомца</h1>
<div class="content_review">
            <div class="form-error">{{ from.non_field_errors }}</div>
    <form method="post">
    {% csrf_token %}
        <div class="block_prof_child2">
        <p class="text_bold">{{ form.nickname.label_tag}}</p>
        <p class="text_bold">{{ form.birthdate.label_tag}}</p>
           <p class="text_bold"> {{ form.breed.label_tag}}</p>
            <p class="text_bold">{{ form.color.label_tag}}</p>
               </div>
            <br>
            <div class="block_prof_child2">
        <p>{{ form.nickname}}</p>
         <p><input type="date" id="birthdate" name="birthdate" value="{{ form.birthdate|date:'Y-m-d' }}"></p>
           <p> {{ form.breed}}</p>
            <p>{{ form.color}}</p>

        </div>
    <p><button class="btn btn-outline-dark" type="submit">Добавить питомца</button></p>
    </form>
</div>


{% endblock %}

homejango/users/templates/users/edit_pet.html
{% extends 'main/layout.html' %}
{% load static %}

{% block content %}
<h1 class="main_h">Изменение данных питомца</h1>
<div class="content_review">
    <div class="form-error">{{ form.non_field_errors }}</div>
    <form method="post">
        {% csrf_token %}
        <div class="block_prof_child2">
            <p class="text_bold">{{ form.nickname.label_tag }}</p>
            <p class="text_bold">{{ form.birthdate.label_tag }}</p>
            <p class="text_bold">{{ form.breed.label_tag }}</p>
            <p class="text_bold">{{ form.color.label_tag }}</p>
        </div>
        <br>
        <div class="block_prof_child2">
            <p>{{ form.nickname }}</p>
           <p><input type="date" name="birthdate" value="{{ form.instance.birthdate|date:'Y-m-d' }}"></p>
            <p>{{ form.breed }}</p>
            <p>{{ form.color }}</p>
        </div>
        <p><button class="btn btn-outline-dark" type="submit">Сохранить изменения</button></p>
    </form>
</div>
{% endblock %}

homejango/users/templates/users/login.html
{% extends 'main/layout.html' %}
{% load static %}

{% block content %}
<h1 class="main_h">Авторизация</h1>
<div class="content_review_reg">
<div class="form-error">{{ from.non_field_errors }}</div>
<form method="post">
{% csrf_token %}
<div class="block_prof_child2">
    <p class="text_bold">{{ form.username.label_tag}}</p>
    <p class="text_bold">{{ form.password.label_tag}}</p>
</div>
<div class="block_prof_child2">
<p>{{ form.username}}</p>
<p>{{ form.password}}</p>
</div>

<p><button class="btn btn-outline-dark" type="submit">Войти</button></p>


</form>
</div>
{% endblock %}

homejango/users/templates/users/profile.html
{% extends 'main/layout.html' %}
{% load static %}

{% block content %}
<h1 class="main_h">Профиль</h1>


<div class="block_prof">
    <div class="form-error">{{ from.non_field_errors }}</div>
    <form method="post">
         {% csrf_token %}
        <p class="block_prof_child text_bold text_big_size">Ваши данные</p>
        <p class="block_prof_child text_bold">Чтобы изменить данные внесите изменения в нужные поля и нажмите сохранить.
        Чтобы добавить питомца - введите данные в пустые поля и нажмите сохранить</p>

        <div class="block_prof_child">

            <div class="block_prof_child2">
        <p class="text_bold">{{ form.username.label_tag}}</p>
        <p class="text_bold">{{ form.email.label_tag}}</p>
           <p class="text_bold"> {{ form.first_name.label_tag}}</p>
            <p class="text_bold">{{ form.last_name.label_tag}}</p>
            <p class="text_bold">{{ form.phone.label_tag}}</p>
             </div>
            <br>
            <div class="block_prof_child4">
        <p>{{ form.username}}</p>
        <p>{{ form.email}}</p>
           <p> {{ form.first_name}}</p>
            <p>{{ form.last_name}}</p>
           <p> {{ form.phone}} </p>
                </div>
                <div class="block_prof_child4">
                    <p><button class="btn btn-outline-dark" type="submit">Обновить данные</button></p>
                             <a href="{% url 'users:profile_add_pet' %}">
                                <button type="button" class="btn btn-outline-dark">Добавить питомца</button>
                              </a>
                    </div>

        </div>
        <p class="block_prof_child text_bold text_big_size">Ваши питомцы</p>
        <div class="block_prof_child">

              <div class="block_prof_child3">
                   {% if pets %}
                    <p class="text_bold"> Кличка питомца </p>
                    <p class="text_bold"> Дата рождения</p>
                   <p class="text_bold"> Порода</p>
                    <p class="text_bold">Окрас</p>
                </div>
             <div class="block_prof_child3">
                    {% for el in pets %}
                    <p class="borders">{{ el.nickname }}</p>
                   <p class="borders"> {{ el.birthdate }}</p>
                   <p class="borders"> {{ el.breed }}</p>
                   <p class="borders"> {{ el.color }}</p>
                             <a href="{% url 'users:profile_delete' el.id %}">
                                <button type="button" class="btn btn-outline-dark btn_pofile">Удалить</button>
                              </a>
                            <a href="{% url 'users:profile_edit_pet' el.id %}">
                                <button type="button" class="btn btn-outline-dark">Отредактировать</button>
                              </a>
                         <br>

                    {% endfor %}
                 </div>
                    {% else %}
                 <p class="block_prof_child5">Вы не добавили ни одного питомца</p>
                     {% endif %}

                </div>

        </div>



    </form>
</div>
<script>
            $(document).ready(function(){
          $('[data-toggle="tooltip"]').tooltip();
        });
</script>
{% endblock %}

homejango/users/templates/users/register.html
{% extends 'main/layout.html' %}
{% load static %}

{% block content %}
<h1 class="main_h">Регистрация</h1>


<div class="form-error">{{ from.non_field_errors }}</div>
<form method="post">
{% csrf_token %}
<div class="content_review_reg">
<div class="content_review_reg_child">
    <p class="text_bold">{{ form.username.label_tag}}</p>
    <p class="text_bold">{{ form.email.label_tag}}</p>
    <p class="text_bold">{{ form.password1.label_tag}}</p>
    <p class="text_bold">{{ form.password2.label_tag}}</p>
    <p class="text_bold">{{ form.first_name.label_tag}}</p>
    <p class="text_bold">{{ form.last_name.label_tag}}</p>
    <p class="text_bold">{{ form.phone.label_tag}}</p>
</div>
<div class="content_review_reg_child">
<p>{{ form.username}}</p>
<p>{{ form.email}}</p>
<p>{{ form.password1}}</p>
<p>{{ form.password2}}</p>
<p>{{ form.first_name}}</p>
<p>{{ form.last_name}}</p>
<p>{{ form.phone}}</p>

</div>
 <p><button class="btn btn-outline-dark height_auto" type="submit">Регистрация</button></p>


</div>

</form>

{% endblock %}

homejango/users/templates/users/register_done.html
{% extends 'main/layout.html' %}
{% load static %}

{% block content %}
<h1 class="main_h">Спасибо за регистрацию</h1>

<div class="content_review">
<p>Спасибо за регистрацию</p>

</div>
{% endblock %}