homejango/homejango/urls.py
from django.contrib import admin
from django.urls import path, include  # include добавленный вручную метод для вывода url
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include('main.urls')),
                  path('users/', include('users.urls', namespace='users')),
                  path('service/', include('service.urls')),
              ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += [
        path('__debug__/', include(debug_toolbar.urls, namespace='djdt')),
    ]

homejango/main/urls.py
from django.urls import path
from . import views
from .views import ReviewsListView, ReviewCreateView

urlpatterns = [
   path('', views.index, name='home'),
   path('about', views.about, name='about'),
   path('contacts', views.contacts, name='contacts'),
   # path('reviews', views.reviews, name='reviews'),
   path('reviews/delete/<int:pk>/', views.ReviewDelete.as_view(), name='reviews_delete'),
   # path('reviews/delete/<int:id>/', views.reviews_delete, name='reviews_delete'),
   path('reviews/', ReviewsListView.as_view(), name='reviews-list'),
   path('reviews/add/', ReviewCreateView.as_view(), name='review-add'),
   # path('reviews', views.reviews, name='reviews'),
   # path('reviews/delete/<int:id>/', views.reviews_delete, name='reviews_delete'),
   path('personal_doctor', views.personal_doctor, name='personal_doctor'),
   path('gruming', views.gruming, name='gruming'),
]

homejango/users/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path
from . import views


app_name = 'users'
urlpatterns = [
   # для вывода нужной страницы после входа/выхода нужно прописать или
   # функции get-succes_url или в settings  LOGOUT/LOGIN_REDIRECT_URL
   path('login/', views.LoginUser.as_view(), name='login'),     # для
   path('logout/', LogoutView.as_view(), name='logout'),
   path('register/', views.RegisterUser.as_view(), name='register'),
   path('profile/', views.ProfileUser.as_view(), name='profile'),
   # path('profile/', views.profile_update, name='profile'),
   path('profile/delete/<int:pk>/', views.PetsDelete.as_view(), name='profile_delete'),
   # path('profile/add_pet/', views.profile_add_pet, name='profile_add_pet'),

# большая разница между <int:temp_id>  и <int:pk>. В первом случае просто указываем что это число
   # подходит для функций. Если используем класс надо четко указать id(<int:pk>) или slug
   path('profile/add_pet/', views.AddPets.as_view(), name='profile_add_pet'),
   path('profile/edit_pet/<int:pk>/', views.UpdatePets.as_view(), name='profile_edit_pet'),
]

homejango/main/models.py
from django.db import models

# Create your models here.


class Reviews(models.Model):
    name = models.CharField('Название отзыва', max_length=30)
    description = models.TextField('Текст отзыва')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Отзывы/Reviews'
        verbose_name_plural = 'Отзывы/Reviews'

homejango/main/forms.py
from django.forms import ModelForm, TimeInput, TextInput, Textarea
from .models import Reviews


class ReviewsForms(ModelForm):
    class Meta:
        model = Reviews
        fields = ['name', 'description']

        widgets = {
            'name': TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Краткое описание',
                'maxlength': '30',
            }),
            'description': Textarea(attrs={
                'class': 'form-control',
                'placeholder': 'Полный текст отзыва',
            })

        }

homejango/main/views.py
from django.contrib.auth.models import Permission
from django.contrib.contenttypes.models import ContentType
from django.core.checks import messages
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView, DeleteView

from .forms import ReviewsForms
from .models import Reviews


# Create your views here.
def index(request):
    date = {
        'title': 'Домашняя страница',
    }
    return render(request, 'main/index.html', date)


def about(request):
    return render(request, 'main/about.html')


def contacts(request):
    return render(request, 'main/contacts.html')


class ReviewsListView(ListView):
    model = Reviews
    context_object_name = 'reviews'
    template_name = 'main/reviews.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = ReviewsForms()
        return context


class ReviewCreateView(CreateView):
    model = Reviews
    form_class = ReviewsForms
    template_name = 'main/reviews.html'
    success_url = reverse_lazy('reviews-list')  # URL для перенаправления после создания отзыва

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['reviews'] = Reviews.objects.all()
        return context

    def form_valid(self, form):
        form.save()
        return super().form_valid(form)

#
# def reviews(request):
#     if request.POST:
#         temp_name = request.POST['name']
#         temp_description = request.POST['description']
#         reviews_obj = Reviews(name=temp_name, description=temp_description)
#         reviews_obj.save()
#
#     form = ReviewsForms()
#     reviews = Reviews.objects.all()
#     context = {
#         'reviews': reviews,
#         'form': form
#
#     }
#     return render(request, 'main/reviews.html', context)

class ReviewDelete(DeleteView):
    model = Reviews
    success_url = reverse_lazy('reviews-list')

    def delete(self, request, *args, **kwargs):
        messages.success(self.request, "Отзыв успешно удален")
        return super().delete(request, *args, **kwargs)

    def get(self, request, *args, **kwargs):   # переорпеделение мтеода удаления (без вызова подтверждения)
        self.object = self.get_object()
        self.object.delete()
        return redirect(self.get_success_url())

# def reviews_delete(request, id):
#     reviews_to_delete = Reviews.objects.filter(id=id)
#     reviews_to_delete.delete()
#
#     form = ReviewsForms()
#     reviews = Reviews.objects.all()
#     context = {
#         'reviews': reviews,
#         'form': form
#
#     }
#     return render(request, 'main/reviews.html', context)
#

def personal_doctor(request):
    return render(request, 'main/personal_doctor.html')


def gruming(request):
    return render(request, 'main/gruming.html')

homejango/main/templates/main/contacts.html
{% extends 'main/layout.html' %}


{% block content %}
<h1 class="main_h">Контакты</h1>
<p class="content_review">Если вы захотите материально отблагодарить создателя сего
    "шедевра". Можете стучаться в почту saatarko@tut.by.
А так же меня можно найти где-то тут</p>

<iframe class="google_map" src="https://www.google.com/maps/embed?pb=!1m14!1m12!1m3!1d42232.377837461965!2d27.498552516850165!3d53.88646013095581!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!5e0!3m2!1sru!2sby!4v1718045242097!5m2!1sru!2sby"  style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>






{% endblock %}

homejango/main/templates/main/gruming.html
{% extends 'main/layout.html' %}
{% load static %}

{% block title %} Груминг" {% endblock %}
{% block content %}
<h1 class="main_h">Груминг</h1>

<div class="content">
<p class="main_text">Регулярная стрижка домашнего питомца — простой способ
    поддерживать его гигиену и здоровье. Колтуны в шерсти или слишком
    длинная шерсть доставляют питомцу дискомфорт, особенно летом, и
    даже могут привести к дерматологическим заболеваниям. В период линьки стрижка
    спасает владельцев от ежедневной уборки шерсти, котов и собак — от изнывания в жару.
    Модельная стрижка собаки или кота подчеркивает принадлежность к определенной породе.
    </p>
   <p class="main_text"> Груминг можно проводить уже с 3 месяцев 1-2 раза в месяц. Тип стрижки подбирается индивидуально в зависимости от типа шерсти, породы и пожеланий хозяина.

Процедура проводится под миорелаксантом, чтобы питомец не нервничал.

Что входит в услугу груминга
Понятие груминга шире, чем просто стрижка. Это целый комплекс гигиенических процедур, которые придают собаке или кошке ухоженный вид, а вместе с тем и облегчают последующий уход за питомцем.

Это и чистка ушей, и удаление из них лишних волосков, и подстригание когтей, и выстригание излишков шерсти между подушечками. Также гигиенический груминг подразумевает "санитарную" стрижку, когда шерсть срезается в паху и под хвостом.

Такую обработку питомца рекомендуется проводить раз в 2-4 недели. После гигиенического груминга ухаживать за любимцем гораздо легче.

Стрижка по корпусу производится по желанию владельца.

Таким образом, комплекс гигиенических процедур для собаки или кошки, не участвующих в выставках, будет включать:
стрижку когтей, выбривание шерсти между подушечками лап;
удаление шерсти в ушах, их чистка;
чистку зубов при необходимости;
чистка параанальных желез при необходимости;
расчесывание или удаление колтунов;
промывку, сушку шерсти;
стрижку и укладку по корпусу, по желанию владельца.
Стрижка особенно необходима в летний период для кошек, чтобы удалить подшерсток, для собак, чтобы снизить риск подцепить клеща или запутаться в репейнике.

Не только эстетика
Груминг – это профилактика и ранняя диагностика кожных, ушных и других заболеваний питомца.

Наша ветеринарная клиника осуществляет чистку и стрижку с использованием высококачественных моющих и ухаживающих средств, индивидуально подбирающихся для животного. Они позволяют надолго сохранять аккуратный внешний вид питомца, улучшают состояние шерсти и кожи, препятствуют появлению аллергии или раздражений.

Наши ветеринары используют самое высокотехнологичное и безопасное оборудование, существующее в данный момент. К примеру, это машинки с лезвием, имеющим антимикробное покрытие, не нагревающимся за счет содержания ионов серебра.

В кабинете есть все необходимые инструменты и средства, поэтому никакая предварительная подготовка питомца не нужна.

Найдем подход к вашему любимцу
Животные по-разному переносят стрижку: некоторым особенно неприятно постороннее вмешательство и ограничение их воли. Чтобы избежать лишних волнений и не нервировать питомца, мы проводим груминг под седацией. Это позволяет собаке или кошке с комфортом перенести процедуру и гарантирует аккуратный результат стрижки. При этом чем чаще производится стрижка, тем легче питомец будет ее переносить в дальнейшем.</p>
</div>

{% endblock %}

homejango/main/templates/main/index.html
{% extends 'main/layout.html' %}
{% load static %}

{% block title %} Домашняя страница {% endblock %}
{% block content %}
<h1 class="main_h">Приветствуем Вас в ветеринарной клинике "Кусочек счастья"</h1>

<div class="content">
<img src="{% static 'main/img/main5.jfif' %}" alt='Кусочек счастья'/>
<p class="main_text">Ветеринарная клиника "Кусочек счастья" основана в 2012 году ветеринарным врачом Сасом Сергеем Николаевичем.
    Изначально была задана высокая планка к профессиональным качествам врачей и других сотрудников, взят вектор на
    высокотехнологическое оснащение, которое позволит более точно диагностировать патологии у собак и кошек и оказывать
    более широкий спектр врачебных манипуляций. Целью было развитие клиники с узкопрофильными специалистами и современным
    оборудованием высокого класса, для обеспечения полного спектра диагностических и лечебных мероприятий в одном месте.
    "Кусочек счастья" - стремление к лучшему!Мы являемся первой клиникой, которая стала проводить черезпросветную
    эндоскопию (гастроскопию, трахеоскопию, отоскопию, риноскопию, колоноскопию, вагиноскопию, цист-уретроскопию),
    что позволило нам диагностировать патологии и помогать животным, которых ранее отправляли в Россию или Литву.
    В первые годы работы клиники мы открыли свою лабораторию, которая позволяет выполнять анализы крови
    за сорок минут и проводить многие другие исследования, стали выполнять УЗИ органов брюшной и грудной клетки собакам
    и кошкам, открыли рентген-кабинет с цифровым аппаратом, что позволяет нам получать снимки высокого качества за 2
    минуты.Уже длительное время мы занимаемся ветеринарной травматологией и ортопедией.</p>
   <p class="main_text"> В клинике есть все необходимое оборудование, расходные материалы (пластины любого размера) для того, чтобы составить перелом как маленькому
    тойчику или котенку, так и огромному догу. Наши специалисты первыми стали выполнять операцию ТПЛО и ТТА при лечении
    разрыва передней крестообразной связки у собак и кошек. Также мы проводим рентгенологическое обследование по раннему
    обнаружению дисплазии тазобедренного сустава у собак.В рядах клиники также находятся узкие врачи-специалисты. Компетентный
    онколог, который прошел стажировку в ветеринарной клинике «Биоконтроль» и получил удостоверение государственного образца.
    Офтальмолог, у которого есть все необходимое оборудование для диагностики патологии глаза у собаки или кошки.
    Невролог-хирург, который сможет купировать эпилептический приступ у собаки и прооперировать позвоночник при грыже
    дисков у собаки.В 2016 году, когда нам стало тесно в помещении на Каховской, мы всей командой переехали на новый
    адрес – переулок Козлова 1, где начали дальнейший свой профессиональный рост.С начала 2017 года мы начали выполнять
    лапароскопические операции – это операция без разрезов, когда все хирургические маневры выполняются под контролем
    камеры в брюшной полости. Это качественно новый этап в проведении операционных вмешательств у животных, за счет
    отсутствия разрезов значительно уменьшается травматизм операции, и животное легче восстанавливается.УЗИ сердца
    собакам и кошкам (ЭХОКГ) и электрокардиограмму мы проводим каждому пациенту перед наркозом, так как грамотная
    работа сердца – это необходимое условие безопасного наркоза. Кроме того, кардиолог сможет назначить дальнейшее
    лечение Вашему любимцу.В нашей клинике вы найдете ВСЕ ВИДЫ ВЕТЕРИНАРНЫХ УСЛУГ: от комплексной ветеринарной
    диагностики до эффективного лечения.</p>

</div>

{% endblock %}

homejango/main/templates/main/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <script src="https://kit.fontawesome.com/045b097978.js" crossorigin="anonymous"></script>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'main/css/main.css' %}">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css">
    <title> {% block title %} {% endblock %}</title>
    {% if messages %}
    <ul class="messages">
        {% for message in messages %}
            <li {% if message.tags %} class="alert alert-info margine_left" role="alert"{% endif %}>{{ message }}</li>
        {% endfor %}
    </ul>
{% endif %}
</head>
<body>

    <aside id="navigation-panel">
    <div class="nav_panel">
        <img src="{% static 'main/img/logo.jpg' %}" alt="Логотип">
                   {% if user.is_authenticated %}
                <p> <a href="{% url 'users:profile' %}">Добро пожаловать {{user.username}}</a></p>
                {% endif %}
        <h3 class="nav_h">Навигация</h3>
        <nav>
            <ul>
                <li><a href="{% url 'home' %}"><i class="fa-solid fa-house-user"></i> Главная</a></li>
                <li onclick="toggleServices(this)">
                    <i class="fa-solid fa-shield-cat"></i> Наши услуги
                    <ul>
                        <li><a href="{% url 'procedure' %}">Процедуры</a></li>
                        <li><a href="{% url 'personal_doctor' %}">Личный врач</a></li>
                        <li><a href="{% url 'gruming' %}">Груминг</a></li>
                    </ul>
                </li>
                <li><a href="{% url 'reviews-list' %}"><i class="fa-regular fa-address-card"></i> Отзывы</a></li>
                <li><a href="{% url 'contacts' %}"><i class="fa-regular fa-address-card"></i> Контакты</a></li>
                 {% if user.username == "Modetaror" or user.username == "Saatarko"%}
                 <li><a href="{% url 'schedule' %}"><i class="fa-regular fa-address-card"></i>Расписание</a></li>
                 {% endif %}
                {% if user.is_authenticated %}
                <li><a href="{% url 'users:logout' %}"><i class="fa-regular fa-address-card"></i>Выход</a></li>
                {% else %}
                <li><a href="{% url 'users:login' %}"><i class="fa-regular fa-address-card"></i> Вход</a> |<a
                        href="{% url 'users:register' %}"><i class="fa-regular fa-address-card"></i>Регистр.</a>
                </li>

                {% endif %}
            </ul>
        </nav>
    </div>
</aside>

    <main>

     {% block content %} {% endblock %}

    </main>

    <div class="flex-container_3">
            <div class="footer">
            <div  class="flex-child_3">
                <a>Домашняя работа по теме Django: Published 2024-05-29. Copyright © 2024 Saatarko</a>
            </div>

            </div>
        </div>

</body>
</html>

<script>
    function toggleServices(liElement) {
        const servicesList = liElement.querySelector("ul");
        servicesList.style.display = servicesList.style.display === "none" ? "block" : "none";
    }
</script>

homejango/main/templates/main/personal_doctor.html
{% extends 'main/layout.html' %}
{% load static %}

{% block title %} Программа "Личный ветеринар" {% endblock %}
{% block content %}
<h1 class="main_h">Программа "Личный ветеринар"</h1>

<div class="content">
<p class="main_text">Наверняка многие из нас, устали от случайных ветврачей, лишних назначений и
    обследований, пропущенных вакцинаций и обработок, хотели бы иметь опытного и
    высококвалифицированного личного ветеринарного врача, который, зная особенности
    поведения Вашего питомца и особенности его организма, мог определить оптимальную
    схему лечения, назначить необходимые обследования и анализы, следить за плановыми
    вакцинациями, вести учет обработок, подбирать и корректировать питание. А хотели бы,
    чтобы его помощь была доступна онлайн или по телефону?Все это можно получить по программе
    "Личный ветеринар".</p>
   <p class="main_text"> Программа:
Ежегодная диспансеризация (комплексное обследование организма). Мониторинг здоровья  питомца с использованием всего спектра диагностического и лечебного оборудования нашего центра;
Консультации узких специалистов: стоматолог, кардиолог, репродуктолог, онколог, хирург, офтальмолог, дерматолог;
Качественная ветеринарная помощь на протяжении 12 месяцев;
Ведение протоколов вакцинации;
Непрерывное наблюдение за здоровьем питомца, что позволяет фиксировать заболевание на ранней стадии и гарантирует эффективность лечения;
Выезд ветеринарного врача на дом, в пределах Минска;
Учет плановых обработок от гельминтов и эктопаразитов;
Помощь в поиске ветеринарных препаратов и их аналогов;
Экономия времени и средств (долгосрочное ветеринарное обслуживание по годовым договорам предусматривает значительные преимущества по сравнению с разовыми и экстренными обращениями к специалистам, позволяет обойтись без визита к специалисту, если в этом нет необходимости и получить помощь).
Ветеринарная помощь в непредвиденной ситуации.
Заключение договора
Заключение договора на 12 месяцев.
Предоставление оформленного ветеринарного паспорта на питомца с отметкой о чипировании.
Клинический осмотр питомца.
Паспорт владельца животного.
После заключения договора  и внесение предоплаты клиенту выдается: экземпляр договора на оказание ветеринарных услуг.</p>

</div>

{% endblock %}

homejango/main/templates/main/reviews.html
{% extends 'main/layout.html' %}


{% block content %}
<h1 class="main_h">Отзывы</h1>

        <div class="content_review">
            <div class="content_review_child2">
        {% if reviews %}
        {% for el in reviews %}

                    <div>
                        <p class="text_bold"> Отзыв:</p>
                        <p class="text_bold"> {{el.name}}</p> <br>
                        {{el.description}}
                        <hr>
                         {% if user.username == "Modetaror" or user.username == "Saatarko"%}
                        <a href="{% url 'reviews_delete' el.id %}"> <button class="btn btn-outline-dark">Удалить отзыв</button></a>
                         {% endif %}
                    </div>

        {% endfor %}


        {% else %}
            <p class="text_bold">В данный момент отзывов нет</p>
        {% endif %}

        </div>

        {% if user.is_authenticated %}
            <div class="content_review_child2">
                <p class="text_bold">Оставить свой отзыв:</p>
        <form method="post" action="{% url 'review-add' %}">
            {% csrf_token %}
                       <div class="form-group">
                    {{ form.name.label_tag }}
                    {{ form.name }}
                    {{ form.name.errors }}
                </div>
                <div class="form-group">
                    {{ form.description.label_tag }}
                    {{ form.description }}
                    {{ form.description.errors }}
                </div>
                 <button type="submit" class="btn btn-outline-dark">Отправить</button>

           </form>
                </div>
       {% else %}
             <p>Чтобы оставить свой отзыв, необходимо зарегистрироваться! Если Вы уже зарегистрировалисьвойдите в свою учетную запись. </p>

       {% endif %}
        </div>
{% endblock %}